### ISSUE TITLE
Current error with avatar favourites after new build

### ISSUE THREAD

**Issue by physicalmemory** [physicalmemory/FavCat-Restored#1]
>[13:14:35.975] [FavCatRestored] [ERROR] Exception in avatar module init: System.TypeLoadException: Could not resolve type with token 010000a5 (from typeref, class/assembly UiAvatarList, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>  at FavCat.Modules.AvatarModule..ctor () [0x0000b] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.FavCatMod.OnUiManagerInit () [0x00016] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>[13:14:36.139] [FavCatRestored] [ERROR] Exception in world module init: System.TypeLoadException: Could not resolve type with token 010000a5 (from typeref, class/assembly UiAvatarList, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].GatherListsImpl (System.Boolean forOrdering, System.Collections.Generic.List\`1[T] result, UnityEngine.Transform parent) [0x00066] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].GatherLists (System.Boolean forOrdering) [0x00007] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].ReorderLists () [0x0001e] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T]..ctor (UIExpansionKit.API.ExpandedMenu expandedMenu, FavCat.Database.DatabaseFavoriteHandler\`1[T] favoriteHandler, UnityEngine.Transform listsParent, System.Boolean hasUpdateAndCreationDates) [0x001c1] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.WorldsModule..ctor () [0x0001c] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.FavCatMod.OnUiManagerInit () [0x0004a] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>[13:14:36.206] [FavCatRestored] [ERROR] Exception in player module init: System.TypeLoadException: Could not resolve type with token 010000a5 (from typeref, class/assembly UiAvatarList, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].GatherListsImpl (System.Boolean forOrdering, System.Collections.Generic.List\`1[T] result, UnityEngine.Transform parent) [0x00066] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].GatherLists (System.Boolean forOrdering) [0x00007] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T].ReorderLists () [0x0001e] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.ExtendedFavoritesModuleBase\`1[T]..ctor (UIExpansionKit.API.ExpandedMenu expandedMenu, FavCat.Database.DatabaseFavoriteHandler\`1[T] favoriteHandler, UnityEngine.Transform listsParent, System.Boolean hasUpdateAndCreationDates) [0x001c1] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.Modules.PlayersModule..ctor () [0x0001c] in <5f10430ae7a6445fa050b34c75ba09d5>:0
>  at FavCat.FavCatMod.OnUiManagerInit () [0x00080] in <5f10430ae7a6445fa050b34c75ba09d5>:0

Same error occurring in latest knah build. It's only affecting avatar favourites, world and player favourites are okay.
Appears to be an issue with UiAvatarList, current theory is that this type no longer exists. But then, how to locate and replace with an alternative? This coding thing is hard.

**Comment by physicalmemory** [comment]
~~Most likely an updated type can be found by cracking open VRC.UI~~
I need to be looking at Assembly-CSharp

**Comment by physicalmemory** [comment]
~~On closer inspection these components seem useless to the overall function of avatar favourites. Commenting them out to test.~~
They're important for the individual modules to be rendered against the VRC UI. Can't just comment them out.

**Comment by physicalmemory** [comment]
-snip- me being an idiot and not understanding how code works

**Comment by physicalmemory** [comment]
>The TypeLoadException with a number token (instead of a type name) usually indicates that the assembly used at runtime is different than the one used at compile time.

Interesting... Maybe this is an issue with MelonLoader itself?
Or possibly my own fault potentially using outdated assemblies. But if that were the case then this error should not be being thrown at knah's side unless the assemblies there are also out of date.

**Comment by physicalmemory** [comment]
UiAvatarList definitely still exists, that's not the problem here.

**Comment by physicalmemory** [comment]
Managed to pare the error down to this.
>[15:57:57.286] [FavCatRestored] [ERROR] Exception in avatar module init: System.TypeLoadException: Could not resolve type with token 010000a5 (from typeref, class/assembly UiAvatarList, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>  at FavCat.Modules.AvatarModule..ctor () [0x0000b] in <a34155f9a8d2496ab129ce734887ca65>:0
>  at FavCat.FavCatMod.OnUiManagerInit () [0x00016] in <a34155f9a8d2496ab129ce734887ca65>:0

**Comment by physicalmemory** [comment]
-snip- again me not knowing how code works

**Comment by yobson1** [comment]
my brother in christ: check my fork [here](url). it is updated for 2001.

**Comment by physicalmemory** [comment]
Thank you for this, can't believe I missed it! There must be something I'm persistently missing because building at my end Visual Studio is persistently unable to find UiAvatarList, but looks like you've been able to build it just fine.

**Comment by physicalmemory** [comment]
Closing, error resolved.
